(function(h,l,n){function e(c,b){return(c||"").length>b?c.substr(0,b-3)+"...":c}function k(c,b){if(1!=navigator.doNotTrack){var a=g.extend({},g.track.defaultParams,c,b),d=void 0,f=void 0,d=[];for(f in a)a.hasOwnProperty(f)&&void 0!=a[f]&&""!==a[f]&&d.push(encodeURIComponent(f)+"\x3d"+encodeURIComponent(a[f]));a="https://www.google-analytics.com/collect?"+d.join("\x26");try{navigator.sendBeacon(a)}catch(e){(new Image).src=a}}}function m(c,b,a,d){var f=g.track.timing;c.requestStart&&(f(b,"DNS",c.domainLookupEnd-
c.domainLookupStart+.5|0,a,d),f(b,"TCP",(c.secureConnectionStart?c.secureConnectionStart:c.connectEnd)-c.connectStart+.5|0,a,d),f(b,"TTFB",c.responseStart-(c.startTime||c.navigationStart)+.5|0,a,d));c.secureConnectionStart&&f(b,"SSL",c.connectEnd-c.secureConnectionStart+.5|0,a,d)}var g=h[l]=h[l]||{};g.extend=function(){var c=arguments[0],b=[].slice.call(arguments,1),a,d;for(a=0;a<b.length;++a)if(b[a])for(d in b[a])b[a].hasOwnProperty(d)&&void 0!=b[a][d]&&""!==b[a][d]&&(c[d]=b[a][d]);return c};g.track=
{defaultParams:{v:1,tid:n,cid:+new Date,aip:1,ul:navigator.userLanguage||navigator.language,sr:[screen.width,screen.height].join("x"),dl:e(location.href,2048),dt:e(document.title,1500)},timingSamplingRate:.2,pageview:function(c,b,a){k({t:"pageview",dl:e(c,2048),dt:e(b,1500)},a)},event:function(c,b,a,d,f,p){k({t:"event",ec:e(c,150),ea:e(b,500),el:e(a,500),ev:d,ni:f?1:0},p)},timing:function(c,b,a,d,f){36E5>a&&Math.random()<g.track.timingSamplingRate&&k({t:"timing",utc:e(c,150),utv:e(b,500),utt:a,utl:e(d,
500)},f)},exception:function(c,b,a,d){try{var f=b.message?b.name+": "+b.message:/^([^\r\n]+)/.exec(b.stackTrace||b.stack)[1],e=(b.stackTrace||b.stack).replace(/^[^:]+: [^\r\n]+/,"").replace(/\s\(([^)]+)\)/g,"@$1").replace(/[\r\n](\s*at)?\s+/g," \x3e ").replace(/https?:\/\/[^/]+/ig,"...");g.track.event(c,f+" "+e,a,null,null,d)}catch(h){}},social:function(c,b,a,d){k({t:"social",sn:e(c,50),sa:e(b,50),st:e(a||location.href,2048)},d)},resourcePerformance:function(c,b,a,d){try{var f=h.performance.getEntriesByType("resource"),
e,g;for(e=0;e<f.length;++e)if(g=f[e],c.test(g.name)){m(g,b,a,d);break}}catch(k){}},pagePerformance:function(c,b,a){try{m(h.performance.timing,c,b,a)}catch(d){}}}})(window,"eaio",(window.eproxy||{trackingID:"UA-7427410-88"}).trackingID);
(function(){function b(){try{if(window.performance&&window.performance.getEntriesByType){var b=window.performance.getEntriesByType("resource"),c,a,d=/(https?\/.+)/i.exec(location.href)[1].replace(/^(https?)\//i,"$1://");for(c=0;c<b.length;++c)if(a=b[c],!(/^data:/i.test(a.name)||/https?:\/\/(localhost|127.0.0.1)(:\d+)?\//i.test(a.name)||(new RegExp("^"+location.origin)).test(a.name)||/^https:\/\/www\.google-analytics\.com\/collect/.test(a.name))&&"about:blank"!==a.name){eaio.track.event("resources-on-different-domains",
d,a.name);break}}}catch(e){eaio.track.exception("resources-on-different-domains",e)}}/m/.test(document.readyState)?b():"undefined"!=typeof window.attachEvent?window.attachEvent("onload",b):window.addEventListener&&window.addEventListener("load",b,!1)})();
(function(){function a(){eaio.track.pagePerformance("Proxy")}/m/.test(document.readyState)?a():"undefined"!=typeof window.attachEvent?window.attachEvent("onload",a):window.addEventListener&&window.addEventListener("load",a,!1)})();
(function(){function a(){try{if([].slice.call(document.links).filter(function(a){return/javascript:/i.test(this.href)}).length){var a=/(https?\/.+)/i.exec(location.href)[1].replace(/^(https?)\//i,"$1://");eaio.track.event("javascript-uris",a)}}catch(b){eaio.track.exception("javascript-uris",b)}}/m/.test(document.readyState)?a():"undefined"!=typeof window.attachEvent?window.attachEvent("onload",a):window.addEventListener&&window.addEventListener("load",a,!1)})();
(function(){function a(){try{if(window.performance&&window.performance.getEntriesByType){var a=window.performance.getEntriesByType("resource"),b,c,d=/(https?\/.+)/i.exec(location.href)[1].replace(/^(https?)\//i,"$1://");for(b=0;b<a.length;++b)if(c=a[b],/data:/i.test(c.name)&&/data:(text\/html|text\/x-server-parsed-html|application\/xml+xhtml|image\/svg+xml)'/i.test(c.name)){eaio.track.event("data-uris",d,c.name);break}}}catch(e){eaio.track.exception("data-uris",e)}}/m/.test(document.readyState)?a():
"undefined"!=typeof window.attachEvent?window.attachEvent("onload",a):window.addEventListener&&window.addEventListener("load",a,!1)})();
