(function(h,l,n,p){function g(c,b){return(c||"").length>b?c.substr(0,b-3)+"...":c}function m(c,b,a,d){var f=e.track.timing;c.requestStart&&(f(b,"DNS",c.domainLookupEnd-c.domainLookupStart+.5|0,a,d),f(b,"TCP",(c.secureConnectionStart?c.secureConnectionStart:c.connectEnd)-c.connectStart+.5|0,a,d),f(b,"TTFB",c.responseStart-(c.startTime||c.navigationStart)+.5|0,a,d));c.secureConnectionStart&&f(b,"SSL",c.connectEnd-c.secureConnectionStart+.5|0,a,d)}var e=h[l]=h[l]||{};e.extend=function(){var c=arguments[0],
b=[].slice.call(arguments,1),a,d;for(a=0;a<b.length;++a)if(b[a])for(d in b[a])b[a].hasOwnProperty(d)&&void 0!=b[a][d]&&""!==b[a][d]&&(c[d]=b[a][d]);return c};e.track=function(c,b){if(1!=navigator.doNotTrack){var a=e.extend({},e.track.defaultParams,c,b),d=void 0,f=void 0,d=[];for(f in a)a.hasOwnProperty(f)&&void 0!=a[f]&&""!==a[f]&&d.push(encodeURIComponent(f)+"\x3d"+encodeURIComponent(a[f]));a="https://www.google-analytics.com/collect?"+d.join("\x26");try{navigator.sendBeacon(a)}catch(k){(new Image).src=
a}}};e.track.defaultParams={v:1,tid:n,dh:p,cid:+new Date,aip:1,ul:navigator.userLanguage||navigator.language};e.track.timingSamplingRate=.2;e.track.pageview=function(c,b,a){e.track({t:"pageview",dl:g(c,2048),dt:g(b,1500)},a)};e.track.event=function(c,b,a,d,f,k){e.track({t:"event",ec:g(c,150),ea:g(b,500),el:g(a,500),ev:d,ni:f?1:0},k)};e.track.timing=function(c,b,a,d,f){36E5>a&&Math.random()<e.track.timingSamplingRate&&e.track({t:"timing",utc:g(c,150),utv:g(b,500),utt:a,utl:g(d,500)},f)};e.track.exception=
function(c,b,a,d){try{var f=b.message?b.name+": "+b.message:/^([^\r\n]+)/.exec(b.stackTrace||b.stack)[1],k=(b.stackTrace||b.stack).replace(/^[^:]+: [^\r\n]+/,"").replace(/\s\(([^)]+)\)/g,"@$1").replace(/[\r\n](\s*at)?\s+/g," \x3e ").replace(/https?:\/\/[^/]+/ig,"...");e.track.event(c,f+" "+k,a,null,null,d)}catch(g){}};e.trackResourcePerformance=function(c,b,a,d){try{var f=h.performance.getEntriesByType("resource"),e,g;for(e=0;e<f.length;++e)if(g=f[e],c.test(g.name)){m(g,b,a,d);break}}catch(l){}};
e.trackPagePerformance=function(c,b,a){try{m(h.performance.timing,c,b,a)}catch(d){}}})(window,"eaio",(window.eproxy||{trackingID:"UA-7427410-88"}).trackingID,(window.eproxy||{hostName:location.hostname}).hostName);
(function(){function e(c){var a=c;try{a=/(https?\/.+)/i.exec(c)[1].replace(/^(https?)\//i,"$1://")}catch(b){}return a}function d(){var c=window.performance.getEntriesByType("resource"),a,b,d=e(location.href);for(a=0;a<c.length;++a)b=c[a],/^data:/i.test(b.name)||/https?:\/\/(localhost|127.0.0.1)(:\d+)?\//i.test(b.name)||b.name.startsWith(location.origin)||b.name.startsWith("https://www.google-analytics.com/collect")||eaio.track.event("ResourceOnDifferentDomains",d,e(b.name))}/m/.test(document.readyState)?
d():"undefined"!=typeof window.attachEvent?window.attachEvent("onload",d):window.addEventListener&&window.addEventListener("load",d,!1)})();
(function(){function a(){eaio.trackPagePerformance("Proxy")}/m/.test(document.readyState)?a():"undefined"!=typeof window.attachEvent?window.attachEvent("onload",a):window.addEventListener&&window.addEventListener("load",a,!1)})();
(function(){function b(c){var a=c;try{a=/(https?\/.+)/i.exec(c)[1].replace(/^(https?)\//i,"$1://")}catch(b){}return a}function a(){if([].slice.call(document.links).filter(function(a){return/^javascript:/i.test(this.href)}).length){var a=b(location.href);eaio.track.event("TrackJavaScriptURIs",a)}}/m/.test(document.readyState)?a():"undefined"!=typeof window.attachEvent?window.attachEvent("onload",a):window.addEventListener&&window.addEventListener("load",a,!1)})();
