#!/bin/bash
find src/main -type f \( -name '*.groovy' -or -name '*.java' \) -exec grep -ER '@RequestMapping' \{\} \+ | grep -Eo '[^/]+:.+$' | \
 sed "s/\.groovy\|\.java//;s/@RequestMapping([^\"']*[\"']//;s/[\"'].*\$//" | awk '{print($2, $1)}' | sed 's/:$//' | sort | column -t
