name: Reproduce Jacoco Race Condition Issue

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Run Maven tests multiple times
      run: |
        for i in {1..25}; do
          echo "Run $i"
          mvn clean test | tee log$i.log >/dev/null
          ls -l target/jacoco.exec
        done
