name: Reproduce Jacoco Race Condition Issue

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: Run tests multiple times to reproduce the issue
      run: |
        for i in $(seq 1 25); do
          echo "Run #$i"
          mvn clean test
          if [ -f target/jacoco.exec ]; then
            echo "JaCoCo coverage file exists for run #$i"
            ls -lh target/jacoco.exec
          else
            echo "JaCoCo coverage file missing for run #$i"
          fi
        done
