name: JaCoCo Test Race Condition

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Display Java version
        run: java -version

      - name: Display Maven version
        run: mvn -version

      - name: Run tests multiple times to reproduce the issue
        run: |
          for i in $(seq 1 25); do
            echo "Run #$i"
            mvn clean test
            if [ -f target/jacoco.exec ]; then
              echo "JaCoCo coverage file exists for run #$i"
              ls -lh target/jacoco.exec
            else
              echo "JaCoCo coverage file missing for run #$i"
            fi
          done
